import * as NodeServices from "@effect/platform-node/NodeServices";
import { assert, it } from "@effect/vitest";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";

import { materializeCodexProxyHome, renderCodexProxyConfigToml } from "./CodexProxyHome.ts";

it("renders the q1code model provider block with the bearer header", () => {
  assert.equal(
    renderCodexProxyConfigToml({ baseUrl: "http://127.0.0.1:8317", apiKey: 'k"1' }),
    [
      "# Generated by q1code. Overwritten on every sidecar start.",
      'model_provider = "q1code"',
      "",
      "[model_providers.q1code]",
      'name = "q1code CLIProxyAPI"',
      'base_url = "http://127.0.0.1:8317/v1"',
      'wire_api = "responses"',
      'http_headers = { Authorization = "Bearer k\\"1" }',
      "",
    ].join("\n"),
  );
});

it.layer(NodeServices.layer)("CodexProxyHome", (it) => {
  it.effect("writes config.toml and shares non-auth state from the real Codex home", () =>
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;
      const path = yield* Path.Path;
      const root = yield* fs.makeTempDirectoryScoped({ prefix: "q1code-codex-home-" });
      const shared = path.join(root, "dot-codex");
      const home = path.join(root, "managed");
      for (const entry of ["sessions", "skills", "log", "memories"]) {
        yield* fs.makeDirectory(path.join(shared, entry), { recursive: true });
      }
      yield* fs.writeFileString(path.join(shared, "auth.json"), "{}");
      yield* fs.writeFileString(path.join(shared, "config.toml"), 'model = "x"');
      yield* fs.writeFileString(path.join(shared, "history.jsonl"), "");
      yield* fs.makeDirectory(home, { recursive: true });
      yield* fs.makeDirectory(path.join(home, "skills"));

      const endpoint = { baseUrl: "http://127.0.0.1:9000", apiKey: "k" };
      yield* materializeCodexProxyHome({ homeDir: home, endpoint, sharedHomeDir: shared });

      const config = yield* fs.readFileString(path.join(home, "config.toml"));
      assert.equal(config, renderCodexProxyConfigToml(endpoint));
      assert.equal((yield* fs.stat(path.join(home, "config.toml"))).mode & 0o777, 0o600);
      assert.equal(yield* fs.readLink(path.join(home, "sessions")), path.join(shared, "sessions"));
      assert.equal(
        yield* fs.readLink(path.join(home, "history.jsonl")),
        path.join(shared, "history.jsonl"),
      );
      // Auth and runtime-local entries stay out; an existing real directory is left alone.
      for (const entry of ["auth.json", "log", "memories"]) {
        assert.isFalse(yield* fs.exists(path.join(home, entry)));
      }
      assert.isFalse((yield* fs.stat(path.join(home, "skills"))).type === "SymbolicLink");

      // Idempotent, and a stale link is repointed.
      yield* fs.remove(path.join(home, "sessions"));
      yield* fs.symlink(path.join(root, "elsewhere"), path.join(home, "sessions"));
      yield* materializeCodexProxyHome({ homeDir: home, endpoint, sharedHomeDir: shared });
      assert.equal(yield* fs.readLink(path.join(home, "sessions")), path.join(shared, "sessions"));
    }).pipe(Effect.scoped),
  );

  it.effect("only writes config.toml when there is no real Codex home", () =>
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;
      const path = yield* Path.Path;
      const root = yield* fs.makeTempDirectoryScoped({ prefix: "q1code-codex-home-" });
      const home = path.join(root, "managed");
      yield* materializeCodexProxyHome({
        homeDir: home,
        endpoint: { baseUrl: "http://127.0.0.1:9000", apiKey: "k" },
        sharedHomeDir: path.join(root, "missing"),
      });
      assert.deepEqual(yield* fs.readDirectory(home), ["config.toml"]);
      assert.equal((yield* fs.stat(home)).mode & 0o777, 0o700);
    }).pipe(Effect.scoped),
  );
});
