/**
 * A managed `CODEX_HOME` that routes Codex through the sidecar with no seam:
 * `config.toml` declares `model_providers.q1code` (OpenAI Responses wire API
 * against the proxy, bearer key as a static header) and selects it. A later
 * Accounts UI registers a `codex` provider instance whose `homePath` is this
 * directory; until then a user can set it by hand in Settings.
 *
 * Non-auth state (sessions, skills, sqlite, ...) is symlinked from the user's
 * real `~/.codex` the way upstream's shadow-home overlay does, so history and
 * skills are shared. Limitation: the user's own `~/.codex/config.toml` is not
 * merged; only the proxy block is written.
 */
import * as NodeOS from "node:os";

import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import type * as PlatformError from "effect/PlatformError";
import * as Schema from "effect/Schema";

import type { PrismEndpoint } from "./PrismEnvironment.ts";

export const CODEX_PROXY_PROVIDER_ID = "q1code";

/** Entries of the real Codex home that stay private to it or are runtime-local. Mirrors upstream's `CodexHomeLayout`. */
const UNSHARED_ENTRY_NAMES = new Set([
  "auth.json",
  "models_cache.json",
  "config.toml",
  "log",
  "memories",
  "tmp",
]);

/** TOML basic strings accept JSON escapes for the ASCII values written here. */
const tomlString = (value: string) => JSON.stringify(value);

/** Pure: the same endpoint renders the same file. */
export const renderCodexProxyConfigToml = (endpoint: PrismEndpoint): string =>
  [
    "# Generated by q1code. Overwritten on every sidecar start.",
    `model_provider = ${tomlString(CODEX_PROXY_PROVIDER_ID)}`,
    "",
    `[model_providers.${CODEX_PROXY_PROVIDER_ID}]`,
    `name = ${tomlString("q1code CLIProxyAPI")}`,
    `base_url = ${tomlString(`${endpoint.baseUrl}/v1`)}`,
    'wire_api = "responses"',
    `http_headers = { Authorization = ${tomlString(`Bearer ${endpoint.apiKey}`)} }`,
    "",
  ].join("\n");

export class CodexProxyHomeError extends Schema.TaggedErrorClass<CodexProxyHomeError>()(
  "CodexProxyHomeError",
  {
    homeDir: Schema.String,
    operation: Schema.Literals(["makeDirectory", "writeConfig", "link"]),
    cause: Schema.Defect(),
  },
) {
  override get message(): string {
    return `Codex proxy home '${this.homeDir}' failed during ${this.operation}.`;
  }
}

export interface MaterializeCodexProxyHomeInput {
  readonly homeDir: string;
  readonly endpoint: PrismEndpoint;
  /** The user's real Codex home to share state from. Defaults to `~/.codex`; skipped when absent. */
  readonly sharedHomeDir?: string | undefined;
}

export const materializeCodexProxyHome = Effect.fn("prism.codexHome.materialize")(function* (
  input: MaterializeCodexProxyHomeInput,
): Effect.fn.Return<void, CodexProxyHomeError, FileSystem.FileSystem | Path.Path> {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const fail = (operation: CodexProxyHomeError["operation"]) => (cause: unknown) =>
    new CodexProxyHomeError({ homeDir: input.homeDir, operation, cause });

  yield* fs
    .makeDirectory(input.homeDir, { recursive: true })
    .pipe(Effect.mapError(fail("makeDirectory")));
  yield* fs.chmod(input.homeDir, 0o700).pipe(Effect.mapError(fail("makeDirectory")));

  const configPath = path.join(input.homeDir, "config.toml");
  yield* fs
    .writeFileString(configPath, renderCodexProxyConfigToml(input.endpoint))
    .pipe(Effect.andThen(fs.chmod(configPath, 0o600)), Effect.mapError(fail("writeConfig")));

  const sharedHomeDir = path.resolve(input.sharedHomeDir ?? path.join(NodeOS.homedir(), ".codex"));
  if (sharedHomeDir === path.resolve(input.homeDir)) return;
  const sharedExists = yield* fs.exists(sharedHomeDir).pipe(Effect.orElseSucceed(() => false));
  if (!sharedExists) return;

  const entries = yield* fs.readDirectory(sharedHomeDir).pipe(Effect.mapError(fail("link")));
  yield* Effect.forEach(
    entries.filter((entry) => !UNSHARED_ENTRY_NAMES.has(entry)),
    (entry) =>
      ensureLink(fs, path, path.join(sharedHomeDir, entry), path.join(input.homeDir, entry)),
    { discard: true },
  ).pipe(Effect.mapError(fail("link")));
});

type LinkState =
  | { readonly kind: "missing" }
  | { readonly kind: "other" }
  | { readonly kind: "symlink"; readonly target: string };

/** Symlink `target` at `link`; replace a stale symlink, leave a real file or directory alone. */
const ensureLink = Effect.fn("prism.codexHome.ensureLink")(function* (
  fs: FileSystem.FileSystem,
  path: Path.Path,
  target: string,
  link: string,
): Effect.fn.Return<void, PlatformError.PlatformError> {
  const existing = yield* fs.readLink(link).pipe(
    Effect.map((value): LinkState => ({ kind: "symlink", target: value })),
    Effect.catch((error): Effect.Effect<LinkState> =>
      Effect.succeed(error.reason._tag === "NotFound" ? { kind: "missing" } : { kind: "other" }),
    ),
  );
  if (existing.kind === "other") return;
  if (existing.kind === "symlink") {
    if (path.resolve(path.dirname(link), existing.target) === target) return;
    yield* fs.remove(link);
  }
  yield* fs.symlink(target, link);
});
