import * as NodeServices from "@effect/platform-node/NodeServices";
import { assert, it } from "@effect/vitest";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";

import { prismDirectories, renderPrismConfig, writePrismConfig } from "./PrismConfig.ts";

it("renders a deterministic loopback-only config with everything q1code fixes", () => {
  const text = renderPrismConfig({
    port: 8317,
    authDir: "/home/mic/.q1code/prism/auths",
    apiKey: "key-1",
    managementSecret: 'sec"ret',
    routingStrategy: "fill-first",
  });
  assert.equal(
    text,
    [
      "# Generated by q1code. Overwritten on every sidecar start; edit fork.json instead.",
      'host: "127.0.0.1"',
      "port: 8317",
      'auth-dir: "/home/mic/.q1code/prism/auths"',
      "api-keys:",
      '  - "key-1"',
      "remote-management:",
      "  allow-remote: false",
      '  secret-key: "sec\\"ret"',
      "  disable-control-panel: true",
      "  disable-auto-update-panel: true",
      "routing:",
      '  strategy: "fill-first"',
      "  session-affinity: false",
      "quota-exceeded:",
      "  switch-project: true",
      "  switch-preview-model: true",
      "request-retry: 3",
      "debug: false",
      "usage-statistics-enabled: false",
      "logging-to-file: false",
      "request-log: false",
      "ws-auth: true",
      "plugins:",
      "  enabled: false",
      "",
    ].join("\n"),
  );
  assert.equal(
    renderPrismConfig({ authDir: "/a", apiKey: "k", managementSecret: "s" }),
    renderPrismConfig({ authDir: "/a", apiKey: "k", managementSecret: "s" }),
  );
});

it("defaults the port and routing strategy", () => {
  const text = renderPrismConfig({ authDir: "/a", apiKey: "k", managementSecret: "s" });
  assert.include(text, "\nport: 8317\n");
  assert.include(text, '\n  strategy: "round-robin"\n');
});

it.layer(NodeServices.layer)("prism config files", (it) => {
  it.effect("lays the sidecar out under <baseDir>/prism", () =>
    Effect.gen(function* () {
      const path = yield* Path.Path;
      const directories = prismDirectories("/base", path);
      assert.equal(directories.rootDir, path.join("/base", "prism"));
      assert.equal(directories.authsDir, path.join("/base", "prism", "auths"));
      assert.equal(directories.binDir, path.join("/base", "prism", "bin"));
      assert.equal(directories.codexHomeDir, path.join("/base", "prism", "codex-home"));
      assert.equal(directories.configPath, path.join("/base", "prism", "config.yaml"));
      assert.equal(directories.tombstonesPath, path.join("/base", "prism", "tombstones.json"));
    }),
  );

  it.effect("writes the config atomically with owner-only permissions", () =>
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;
      const path = yield* Path.Path;
      const directory = yield* fs.makeTempDirectoryScoped({ prefix: "q1code-prism-config-" });
      const configPath = path.join(directory, "nested", "config.yaml");
      yield* writePrismConfig(configPath, "port: 1\n");
      yield* writePrismConfig(configPath, "port: 2\n");
      assert.equal(yield* fs.readFileString(configPath), "port: 2\n");
      const stat = yield* fs.stat(configPath);
      assert.equal(stat.mode & 0o777, 0o600);
      const leftovers = yield* fs.readDirectory(path.dirname(configPath));
      assert.deepEqual(leftovers, ["config.yaml"]);
    }).pipe(Effect.scoped),
  );
});
