/**
 * The sidecar's on-disk layout under `<baseDir>/cliproxy/` and the generated
 * `config.yaml`. q1code owns the file: it is rendered from `fork.json` plus the
 * two secrets on every sidecar start, so nothing in it is hand-edited. The
 * proxy bcrypt-hashes `remote-management.secret-key` back into the file on
 * load; the next start simply writes the plaintext again.
 */
import { CLIPROXY_DEFAULT_PORT } from "@q1code/core/cliproxy";
import type { CliProxyRoutingStrategy } from "@q1code/core/config";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import * as Schema from "effect/Schema";

export interface CliProxyDirectories {
  /** `<baseDir>/cliproxy`, mode 0700. */
  readonly rootDir: string;
  /** Account files, one JSON per credential. */
  readonly authsDir: string;
  /** Downloaded binaries, `<binDir>/<version>/cli-proxy-api`. */
  readonly binDir: string;
  /** Managed `CODEX_HOME` that points Codex at the proxy. */
  readonly codexHomeDir: string;
  readonly configPath: string;
}

export const cliproxyDirectories = (baseDir: string, path: Path.Path): CliProxyDirectories => {
  const rootDir = path.join(baseDir, "cliproxy");
  return {
    rootDir,
    authsDir: path.join(rootDir, "auths"),
    binDir: path.join(rootDir, "bin"),
    codexHomeDir: path.join(rootDir, "codex-home"),
    configPath: path.join(rootDir, "config.yaml"),
  };
};

export const DEFAULT_CLIPROXY_ROUTING_STRATEGY: CliProxyRoutingStrategy = "round-robin";

export interface CliProxyConfigInput {
  readonly port?: number | undefined;
  readonly authDir: string;
  readonly apiKey: string;
  readonly managementSecret: string;
  readonly routingStrategy?: CliProxyRoutingStrategy | undefined;
}

/** YAML double-quoted scalars accept JSON string syntax, so this is a safe quoter for paths and secrets. */
const yamlString = (value: string) => JSON.stringify(value);

/** Pure: the same input renders the same text. Everything not exposed in `fork.json` is fixed here. */
export const renderCliProxyConfig = (input: CliProxyConfigInput): string =>
  [
    "# Generated by q1code. Overwritten on every sidecar start; edit fork.json instead.",
    'host: "127.0.0.1"',
    `port: ${input.port ?? CLIPROXY_DEFAULT_PORT}`,
    `auth-dir: ${yamlString(input.authDir)}`,
    "api-keys:",
    `  - ${yamlString(input.apiKey)}`,
    "remote-management:",
    "  allow-remote: false",
    `  secret-key: ${yamlString(input.managementSecret)}`,
    "  disable-control-panel: true",
    "  disable-auto-update-panel: true",
    "routing:",
    `  strategy: ${yamlString(input.routingStrategy ?? DEFAULT_CLIPROXY_ROUTING_STRATEGY)}`,
    "  session-affinity: false",
    "quota-exceeded:",
    "  switch-project: true",
    "  switch-preview-model: true",
    "request-retry: 3",
    "debug: false",
    "usage-statistics-enabled: false",
    "logging-to-file: false",
    "request-log: false",
    "ws-auth: true",
    "plugins:",
    "  enabled: false",
    "",
  ].join("\n");

export class CliProxyConfigWriteError extends Schema.TaggedErrorClass<CliProxyConfigWriteError>()(
  "CliProxyConfigWriteError",
  {
    path: Schema.String,
    cause: Schema.Defect(),
  },
) {
  override get message(): string {
    return `Failed to write the CLIProxyAPI config at '${this.path}'.`;
  }
}

/**
 * Write `contents` to `filePath` atomically: a 0600 temp file in the same
 * directory, fsync, rename. The file holds the API key and management secret.
 */
export const writeCliProxyConfig = Effect.fn("cliproxy.writeConfig")(function* (
  filePath: string,
  contents: string,
): Effect.fn.Return<void, CliProxyConfigWriteError, FileSystem.FileSystem | Path.Path> {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const directory = path.dirname(filePath);
  const tempPath = path.join(directory, `.${path.basename(filePath)}.${process.pid}.tmp`);
  yield* Effect.gen(function* () {
    yield* fs.makeDirectory(directory, { recursive: true });
    yield* Effect.scoped(
      Effect.gen(function* () {
        const file = yield* fs.open(tempPath, { flag: "w", mode: 0o600 });
        yield* file.writeAll(new TextEncoder().encode(contents));
        yield* file.sync;
      }),
    );
    yield* fs.chmod(tempPath, 0o600);
    yield* fs.rename(tempPath, filePath);
  }).pipe(
    Effect.catch((cause) =>
      fs
        .remove(tempPath)
        .pipe(
          Effect.ignore,
          Effect.andThen(Effect.fail(new CliProxyConfigWriteError({ path: filePath, cause }))),
        ),
    ),
  );
});
